In [12]:
import torch
from torch.autograd import Variable
import torch.nn.functional as F
import torch.utils.data as Data
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from torch import nn
import os

%matplotlib inline

In [4]:
#STEPS
# read data from file (.npy)
# shuffle rows (dim = 0)
# cut into train and test (test = data[0:30], train = data[30:])
# split into inputs and outputs (x = train[:,0:2], y = train[:,3]) for both train and test
# end up with x, y, x_test, y_test which are torch tensors # x = torch.from_numpy(x)

In [13]:
cwd = os.getcwd()
cwd

'C:\\Users\\Christina'

In [93]:
# read data from file (.npy)
#data = np.loadtxt("data.txt")
#print(data.shape)
#data

In [94]:
data = pd.read_csv('C:\\Users\\Christina\\mydata.txt',names=['c1', 'c2','c3','c4','target'])
data

c1     c2     c3      c4     target
0  126221  86905  24564   20820   4996.608
1  197866  86905  24564  757741  11461.930
2  126221  86905  24564    2082  14996.608
3  197466  86905  24564   76774  12461.930
4  126221  86905  24564    2082  15996.608
5  193866  86905  24564   77774  13461.930
6  126021  86905  24564    2082  14896.608
7  193866  86905  24564    7774  12461.930
8  126621  86905  24564    2082  14596.608
9  192866  86905  24564    7574  10461.930

In [38]:
# shuffle rows (dim = 0)
data = data.iloc[np.random.permutation(len(data))]
data

c1     c2     c3      c4     target
9  192866  86905  24564    7574  10461.930
1  197866  86905  24564  757741  11461.930
7  193866  86905  24564    7774  12461.930
8  126621  86905  24564    2082  14596.608
5  193866  86905  24564   77774  13461.930
4  126221  86905  24564    2082  15996.608
6  126021  86905  24564    2082  14896.608
2  126221  86905  24564    2082  14996.608
3  197466  86905  24564   76774  12461.930
0  126221  86905  24564   20820   4996.608

In [42]:
#split in X, y
#X = data[:,0:4]
#y = data[:,4]
array=data.values
X = array[:,0:4]
Y = array[:,4]

In [76]:
# cut into train and test (test = data[0:30], train = data[30:])
X_train = X[0:7, :]
y_train = y[0:7]
X_test = X[7:,:]
y_test = y[7:]

#X_train=X_train.astype(np.float32)
#y_train=y_train.astype(np.float32)
#X_test=X_test.astype(np.float32)
#y_test=y_test.astype(np.float32)

In [77]:
#torch tensors in order to put them in NN
X_train= torch.from_numpy(X_train)
y_train = torch.from_numpy(y_train)
X_test = torch.from_numpy(X_test)
y_test = torch.from_numpy(y_test)
X_train, y_train, X_test, y_test

(tensor([[192866.,  86905.,  24564.,   7574.],
         [197866.,  86905.,  24564., 757741.],
         [193866.,  86905.,  24564.,   7774.],
         [126621.,  86905.,  24564.,   2082.],
         [193866.,  86905.,  24564.,  77774.],
         [126221.,  86905.,  24564.,   2082.],
         [126021.,  86905.,  24564.,   2082.]], dtype=torch.float64),
 tensor([10461.9300, 12461.9300, 14996.6080, 15996.6080, 12461.9300, 11461.9300,
         14596.6080], dtype=torch.float64),
 tensor([[126221.,  86905.,  24564.,   2082.],
         [197466.,  86905.,  24564.,  76774.],
         [126221.,  86905.,  24564.,  20820.]], dtype=torch.float64),
 tensor([14896.6080, 13461.9300, 14996.6080], dtype=torch.float64))

In [52]:
y_train.shape

torch.Size([7])

### Model 1

In [88]:
#define model 1
class Net(torch.nn.Module):
    def __init__(self, n_feature, n_hidden, n_output):
        super(Net, self).__init__()                          #n_feature = 1 (the ti of each yi)
        self.hidden = torch.nn.Linear(n_feature, n_hidden)   # hidden layer (n_hidden = neurons of hidden layer)
        self.predict = torch.nn.Linear(n_hidden, n_output)   # output layer (n_output=1, the correspoding yi of ti)

    def forward(self, x):
        x = F.relu(self.hidden(x))      # activation function for hidden layer
        x = self.predict(x)             # linear output
        return x

In [89]:
net = Net(n_feature=4, n_hidden=3, n_output=1)   #200 hidden neurons, 
#to n_feature einai ta inputs x_train gia ta opoia exw to y_train(power)

In [90]:
optimizer = torch.optim.Adam(net.parameters(), lr=0.1)
loss_func = torch.nn.MSELoss()
net = net.float()

In [92]:
# train the network
EPOCHS = 500
epochs = EPOCHS

for t in range(epochs):
  
    y_pred = net(X_train.float())     # input x and prediction of the model based on x

    loss = loss_func(y_pred, y_train.float())     # must be (1. nn output, 2. target)
    print(loss)
    optimizer.zero_grad()   # clear gradients for next epoch
    loss.backward()         # backpropagation, compute gradients
    optimizer.step()        # apply gradients

tensor(2.8452e+08, grad_fn=<MseLossBackward>)
tensor(1.6758e+08, grad_fn=<MseLossBackward>)
tensor(1.6905e+08, grad_fn=<MseLossBackward>)
tensor(1.5581e+08, grad_fn=<MseLossBackward>)
tensor(1.6338e+08, grad_fn=<MseLossBackward>)
tensor(1.6213e+08, grad_fn=<MseLossBackward>)
tensor(1.5421e+08, grad_fn=<MseLossBackward>)
tensor(1.6667e+08, grad_fn=<MseLossBackward>)
tensor(1.5471e+08, grad_fn=<MseLossBackward>)
tensor(1.6002e+08, grad_fn=<MseLossBackward>)
tensor(1.6070e+08, grad_fn=<MseLossBackward>)
tensor(1.5315e+08, grad_fn=<MseLossBackward>)
tensor(1.6141e+08, grad_fn=<MseLossBackward>)
tensor(1.5577e+08, grad_fn=<MseLossBackward>)
tensor(1.5489e+08, grad_fn=<MseLossBackward>)
tensor(1.5940e+08, grad_fn=<MseLossBackward>)
tensor(1.5332e+08, grad_fn=<MseLossBackward>)
tensor(1.5640e+08, grad_fn=<MseLossBackward>)
tensor(1.5671e+08, grad_fn=<MseLossBackward>)
tensor(1.5297e+08, grad_fn=<MseLossBackward>)
tensor(1.5658e+08, grad_fn=<MseLossBackward>)
tensor(1.5457e+08, grad_fn=<MseLos

In [97]:
#define model 2
net2 = torch.nn.Sequential(
        torch.nn.Linear(4, 3),
        torch.nn.LeakyReLU(),
        torch.nn.Linear(3, 1),
    )
optimizer = torch.optim.Adam(net.parameters(), lr=0.5)
loss_func = torch.nn.MSELoss() 
net2 = net2.float()

In [101]:
#training

# start training
for t in range(500):
  
    prediction = net2(X_train.float())     # input x and predict based on x

    loss = loss_func(prediction, y_train.float())     
    print(loss)
    optimizer.zero_grad()   # clear gradients for next train
    loss.backward()         # backpropagation, compute gradients
    optimizer.step()        # apply gradients

tensor(3.0209e+08, grad_fn=<MseLossBackward>)
tensor(3.0209e+08, grad_fn=<MseLossBackward>)
tensor(3.0209e+08, grad_fn=<MseLossBackward>)
tensor(3.0209e+08, grad_fn=<MseLossBackward>)
tensor(3.0209e+08, grad_fn=<MseLossBackward>)
tensor(3.0209e+08, grad_fn=<MseLossBackward>)
tensor(3.0209e+08, grad_fn=<MseLossBackward>)
tensor(3.0209e+08, grad_fn=<MseLossBackward>)
tensor(3.0209e+08, grad_fn=<MseLossBackward>)
tensor(3.0209e+08, grad_fn=<MseLossBackward>)
tensor(3.0209e+08, grad_fn=<MseLossBackward>)
tensor(3.0209e+08, grad_fn=<MseLossBackward>)
tensor(3.0209e+08, grad_fn=<MseLossBackward>)
tensor(3.0209e+08, grad_fn=<MseLossBackward>)
tensor(3.0209e+08, grad_fn=<MseLossBackward>)
tensor(3.0209e+08, grad_fn=<MseLossBackward>)
tensor(3.0209e+08, grad_fn=<MseLossBackward>)
tensor(3.0209e+08, grad_fn=<MseLossBackward>)
tensor(3.0209e+08, grad_fn=<MseLossBackward>)
tensor(3.0209e+08, grad_fn=<MseLossBackward>)
tensor(3.0209e+08, grad_fn=<MseLossBackward>)
tensor(3.0209e+08, grad_fn=<MseLos

### Make predictions

In [ ]:
pred = net(x_test)
pred2 = net2(x_test)

In [ ]:
loss = loss_func(pred, y_test)#oso pio xamilo einai to loss toso kaliteri einai i proseggisi
loss2 = loss_func(pred2, y_test)
float(loss)
float(loss2)

In [ ]:
prediction = net(counters)#prepei na einai tensor tis morfis (1, 3) me integers
prediction